### ISSUE TITLE
Web search özelliğinin iyileştirilmesi

### ISSUE THREAD

**Issue by theilgaz** [acik-kuran/acikkuran-frontend#1]
**Talep**: 

1.  Arama kutucuğuna sure ve ayet bilgileri girilerek doğrudan hedefe ulaşmak.
2. `Sure/Ayet` veya `Sure Ayet` _(Örn. 2/46 veya Bakara 46)_ template'i ile eşleşen sonuçlar için tüm sonuçları gösterme kutucuğunda UX iyileştirmesi

**Mevcut**: Arama sonuçlarında ilk sırada gözükmüyor. "Tüm sonuçları göstermek için tıklayın" seçeneği ile gidince ayete ulaşım mümkün.
**Örnek**: `Bakara 46`
**Ekran Görüntüsü**:

![image](https://user-images.githubusercontent.com/13048645/212040194-c379ea33-7693-43db-8f8b-5d2172adc0c1.png)

**Dipnot**: Next.js çözümü için PR açabilecek erişim sağlanırsa destek olmak isterim.

**Comment by ziegfiroyt** [comment]
> @ziegfiroyt Bunu frontend reposuna taşıyabiliriz.

bu konuyu şu şekilde çözmüştüm ben: 
"bakara 46", "2/46" veya "2:46" yazıldığında quick-search alanında o ayetin detayını yazmak yerine, [2. Bakara suresi 46. ayet](https://acikkuran.com/2/46) şeklinde adresleyen bir satır çıkartıyorum ilk sırada. (bu link haricinde ayrıca enter veya yanındaki search icon'una basılırsa da ilgili sayfaya gidiyor) meilisearch  tarafında çözülebilir bu konu, ama zaten spesifik bir ayet arayan kullanıcının ayetin detay sayfasına gitmesi daha doğru olur. önceki elasticsearch yapısında bu kontrol olmadığı için alakasız sonuçlar geliyordu, şu an doğru çalışıyor bence.

**Comment by theilgaz** [comment]
> @sametcodes
> 
> > @ziegfiroyt Bunu frontend reposuna taşıyabiliriz.
> 
> bu konuyu şu şekilde çözmüştüm ben: "bakara 46", "2/46" veya "2:46" yazıldığında quick-search alanında o ayetin detayını yazmak yerine, [2. Bakara suresi 46. ayet](https://acikkuran.com/2/46) şeklinde adresleyen bir satır çıkartıyorum ilk sırada. (bu link haricinde ayrıca enter veya yanındaki search icon'una basılırsa da ilgili sayfaya gidiyor) meilisearch tarafında çözülebilir bu konu, ama zaten spesifik bir ayet arayan kullanıcının ayetin detay sayfasına gitmesi daha doğru olur. önceki elasticsearch yapısında bu kontrol olmadığı için alakasız sonuçlar geliyordu, şu an doğru çalışıyor bence.

![image](https://github.com/acik-kuran/acikkuran-frontend/assets/13048645/6c4fb217-f33b-4019-a3a8-78ef85bd9690)

Güncel arama sonucu bu şekilde gözüküyor. Teşekkürler!
